=== FoxHash/Modeling/src/main/resources/json_schema/erd_json.schema.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "title" : "Complete erd in json representation",
  "description" : "An complete graphical model in json representation.",
  "type" : "object",
  "properties" : {
    "model_id" : {
      "description" : "Identification of the model",
      "type" : "string"
    },
    "entities" : {
      "description" : "Entities of the graphical model",
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "description" : "Name of the entity",
            "type" : "string"
          },
          "weak_entity" : {
            "description" : "Flag to mark the entity as a weak entity",
            "type" : "boolean"
          },
          "attributes" : {
            "description" : "Connected attributes to this entity",
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                "name" : {
                  "description" : "Name of the attribute",
                  "type" : "string"
                },
                "key" : {
                  "description" : "Is the attribute a key attribute",
                  "type" : "boolean"
                },
                "weak_key" : {
                  "description" : "Is the attribute a weak key attribute",
                  "type" : "boolean"
                },
                "multi_value" : {
                  "description" : "Is the attribute a multi value attribute",
                  "type" : "boolean"
                },
                "derived_value" : {
                  "description" : "Is the attribute a derived value attribute",
                  "type" : "boolean"
                }
              },
              "required" : [
                "name",
                "key",
                "weak_key",
                "multi_value",
                "derived_value"
              ]
            },
            "minItems" : 1
          }
        },
        "required" : [
          "id",
          "weak_entity"
        ]
      }
    },
    "relationships" : {
      "description" : "Relationships of the graphical model",
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "description" : "Name of the relationship.",
            "type" : "string"
          },
          "description" : {
            "description" : "Description of the relationship.",
            "type" : "string"
          },
          "attributes" : {
            "description" : "Connected attributes to this entity",
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                "name" : {
                  "description" : "Name of the attribute",
                  "type" : "string"
                },
                "key" : {
                  "description" : "Is the attribute a key attribute",
                  "type" : "boolean"
                },
                "weak_key" : {
                  "description" : "Is the attribute a weak key attribute",
                  "type" : "boolean"
                },
                "multi_value" : {
                  "description" : "Is the attribute a multi value attribute",
                  "type" : "boolean"
                },
                "derived_value" : {
                  "description" : "Is the attribute a derived value attribute",
                  "type" : "boolean"
                }
              },
              "required" : [
                "name",
                "key",
                "weak_key",
                "multi_value",
                "derived_value"
              ]
            }
          }
        },
        "required" : [
          "id",
          "description"
        ]
      }
    },
    "connections" : {
      "description" : "Connections between the relationships and entities of the graphical model",
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "description" : "Name of the connection",
            "type" : "string"
          },
          "relationship" : {
            "description" : "Name of the relationship which will be connected",
            "type" : "string"
          },
          "entity" : {
            "description" : "Name of the entity which will be connected",
            "type" : "string"
          },
          "cardinality" : {
            "description" : "Cardinality of the connection between the relationship and the entity",
            "type" : "string"
          }
        },
        "required" : [
          "id",
          "relationship",
          "entity",
          "cardinality"
        ]
      }
    },
    "isa-relationships" : {
      "description" : "Is-a relationships of the graphical model",
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "description" : "Name of the is-a relationship.",
            "type" : "string"
          }
        },
        "required" : [
          "id"
        ]
      }
    },
    "isa-connections" : {
      "description" : "Connections between the is-a relationship and the parent entity and the child entities of the graphical model",
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "description" : "Name of the connection",
            "type" : "string"
          },
          "connection_type" : {
            "description" : "Connection type, if the connection should establish to the parent entity or to a child entity.",
            "type" : "string",
            "enum" : [
              "child",
              "parent"
            ]
          },
          "isarelationship" : {
            "description" : "Name of the is-a relationship which will be connected",
            "type" : "string"
          },
          "entity" : {
            "description" : "Name of the entity which will be connected",
            "type" : "string"
          }
        },
        "required" : [
          "id",
          "isarelationship",
          "entity",
          "connection_type"
        ]
      }
    }
  }
}

=== FoxHash/Modeling/src/main/resources/json_schema_test/erd_json_correct.json
{
  "model_id" : "testmodel",
  "entities" : [
    {
      "id" : "Customer",
      "weak_entity" : false,
      "attributes" : [
        {
          "name" : "Name",
          "key" : true,
          "weak_key" : false,
          "compounded_value" : false,
          "multi_value" : false,
          "derived_value" : false
        },
        {
          "name" : "Customer-No",
          "key" : false,
          "weak_key" : false,
          "compounded_value" : false,
          "multi_value" : false,
          "derived_value" : false
        }
      ]
    },
    {
      "id" : "Product",
      "weak_entity" : false,
      "attributes" : [
        {
          "name" : "Date",
          "key" : false,
          "weak_key" : false,
          "compounded_value" : false,
          "multi_value" : false,
          "derived_value" : true
        },
        {
          "name" : "Product-No",
          "key" : true,
          "weak_key" : false,
          "compounded_value" : false,
          "multi_value" : false,
          "derived_value" : false
        }
      ]
    }
  ],
  "relationships" : [
    {
      "id" : "rel01",
      "description" : "purchase"
    }
  ],
  "connections" : [
    {
      "id" : "con01",
      "relationship" : "rel01",
      "entity" : "Customer",
      "cardinality" : "1:1"
    },
    {
      "id" : "con02",
      "relationship" : "rel01",
      "entity" : "Product",
      "cardinality" : "1:n"
    }
  ],
  "isa-relationships": [],
  "isa-connections" : []
}
